name: Feature Request
description: Suggest an enhancement
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got a great idea? Help us improve by sharing your feature suggestion.

  - type: input
    id: title
    attributes:
      label: Feature Summary
      placeholder: Add tracing headers for Kafka messages...

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Help us understand the value.

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How might we implement this?

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      options:
        - Low
        - Medium
        - High
